### ISSUE TITLE
Investigate docker compose ?

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/docker-debian-capitains#1]
- http://anandmanisankar.com/posts/docker-container-nginx-node-redis-example/
- https://github.com/aabdulwahed/Flask-Redis-Docker-Compose/blob/master/docker-compose.yml

What do you think @balmas ? Should we have a docker composer script as well ??

**Comment by balmas** [comment]
It can't hurt, although I reiterate my request that we eventually try for a more general solution that works across docker, vagrant, etc.
