### ISSUE TITLE
problems with Docker/Nemo-Nautilus installation on Mac

### ISSUE THREAD

**Issue by annettegessner** [Capitains/docker-debian-capitains#4]
I've been trying to set up an instance of Nemo-Nautilus on my work Mac (OS X Yosemite version 10.10.5).
I've done everything according to the video Thibault uploaded to YouTube.
Docker is running in VirtualBox (confirmed via running the Hello World program in the console), 
Kitematic is running and showing me exactly the interface I need, 
repository (in this case canonicalLatinLit as in the video) is downloaded and folders repositories and cache are set up according to video, 
Nemo GUI is shown in my browser (Google Chrome, version 50.0.2661.102 (64-bit)), 
there has been no error message popping up anywhere, 
BUT
there's no content shown in the browser, it seems the repository has not been processed or something, I am just being send to the IP address in my browser and the fronten shows up, but no folders or files.

Furthermore, the Cache-folder I created is empty, no matter, what I do.

The Containers Log says the following:

2016-05-10 15:17:33,682 INFO success: nginx entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
app-gunicorn stderr | [2016-05-10 15:18:31 +0000] [28] [DEBUG] GET /
nginx stdout | 192.168.99.1 - - [10/May/2016:15:18:31 +0000] "GET / HTTP/1.1" 200 970 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36"
app-gunicorn stderr | [2016-05-10 15:18:31 +0000] [28] [DEBUG] Closing connection.
app-gunicorn stderr | [2016-05-10 15:18:32 +0000] [24] [DEBUG] GET /favicon.ico
nginx stdout | 192.168.99.1 - - [10/May/2016:15:18:32 +0000] "GET /favicon.ico HTTP/1.1" 404 233 "http://192.168.99.100:32772/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36"
app-gunicorn stderr | [2016-05-10 15:18:32 +0000] [24] [DEBUG] Closing connection.
app-gunicorn stderr | [2016-05-10 15:19:53 +0000] [27] [DEBUG] GET /
nginx stdout | 192.168.99.1 - - [10/May/2016:15:19:53 +0000] "GET / HTTP/1.1" 200 970 "http://192.168.99.100:32772/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36"
app-gunicorn stderr | [2016-05-10 15:19:53 +0000] [27] [DEBUG] Closing connection.

So I guess, the files in my repository are not even processed in any way. 
Thomas seems to have had a similar problem, which could be solved by cloning the repository instead of downloading and unzipping it, but sadly this didn't do the trick for me.
I've tried turning it off and on again and everything, only thing I didn't try is removing Docker completely from my computer and re-installing it.
Soooo, any ideas?

(BTW: I tried installing Nemo on my Windows machine at home and it seemed to have the opposite problem: It didn't stop processing the files in the repository.)

**Comment by PonteIneptique** [comment]
Can you give more logs (complete logs even) and screenshots of settings :) ?

**Comment by annettegessner** [comment]
No problem, I will do that later. What I sent you here was the Container Log from the point, where I clicked on the button to show the repository in the browser. 
In the meantime, maybe you can check out yesterday's hangout on air to see Thomas' theory, that the problem could be due to the fact that our Macs at work have their home directory on a network instead of locally and that maybe Docker can't navigate there.

(Update: canonical-farsiLit is running on my Windows machine at home, so I guess the problem was my computer being unable to process a large repository.)

**Comment by PonteIneptique** [comment]
Ok, try the following : before creating the image and downloading it (when
you click the + sign), click on the three dots. There, change latest to low
memory. And then continue as the tutorial says.

**Comment by annettegessner** [comment]
Here a screenshot of my settings (Macintosh at Uni Leipzig, latest nemo-nautilus):
![image](https://cloud.githubusercontent.com/assets/13348968/15432347/2a488a62-1eae-11e6-8f7d-f7d38c54901c.png)

And the complete containers log:
2016-05-20 15:12:07,524 CRIT Supervisor running as root (no user in config file)
2016-05-20 15:12:07,526 INFO supervisord started with pid 1
2016-05-20 15:12:08,528 INFO spawned: 'stdout' with pid 7
2016-05-20 15:12:08,530 INFO spawned: 'nginx' with pid 8
2016-05-20 15:12:08,531 INFO spawned: 'app-gunicorn' with pid 9
2016-05-20 15:12:10,030 INFO success: stdout entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-05-20 15:12:10,030 INFO success: app-gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
nginx stdout | 2016/05/20 15:12:08 [notice] 8#0: using the "epoll" event method
nginx stdout | 2016/05/20 15:12:08 [notice] 8#0: nginx/1.8.1
nginx stdout | 2016/05/20 15:12:08 [notice] 8#0: OS: Linux 4.4.8-boot2docker
nginx stdout | 2016/05/20 15:12:08 [notice] 8#0: getrlimit(RLIMIT_NOFILE): 1048576:1048576
nginx stdout | 2016/05/20 15:12:08 [notice] 8#0: start worker processes
nginx stdout | 2016/05/20 15:12:08 [notice] 8#0: start worker process 10
app-gunicorn stderr | [2016-05-20 15:12:08 +0000] [9] [DEBUG] Current configuration:
  backlog: 2048
  loglevel: debug
  spew: False
  worker_exit: <function WorkerExit.worker_exit at 0x7f288dd59268>
  tmp_upload_dir: None
  timeout: 30
  preload_app: False
  suppress_ragged_eofs: True
  threads: 2
  paste: None
  errorlog: -
  do_handshake_on_connect: False
  reload: False
  syslog_facility: user
  daemon: False
  worker_tmp_dir: None
  config: None
  proc_name: None
  enable_stdio_inheritance: False
  umask: 0
  logconfig: None
  limit_request_line: 4094
  statsd_prefix: 
  post_request: <function PostRequest.post_request at 0x7f288dd590d0>
  check_config: False
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  post_fork: <function Postfork.post_fork at 0x7f288dd56730>
  on_exit: <function OnExit.on_exit at 0x7f288dd59598>
  pidfile: None
  logger_class: gunicorn.glogging.Logger
  limit_request_fields: 100
  max_requests: 0
  pre_exec: <function PreExec.pre_exec at 0x7f288dd56d90>
  proxy_allow_ips: ['127.0.0.1']
  worker_abort: <function WorkerAbort.worker_abort at 0x7f288dd56bf8>
  ca_certs: None
  limit_request_field_size: 8190
  accesslog: None
  raw_env: []
  user: 0
  forwarded_allow_ips: ['127.0.0.1']
  syslog: False
  worker_connections: 1000
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f288dd568c8>
  pre_request: <function PreRequest.pre_request at 0x7f288dd56f28>
  keyfile: None
  group: 0
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f288dd59400>
  ssl_version: 3
  max_requests_jitter: 0
  sendfile: None
  worker_class: sync
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  default_proc_name: app:app
  on_reload: <function OnReload.on_reload at 0x7f288dd56268>
  when_ready: <function WhenReady.when_ready at 0x7f288dd56400>
  worker_int: <function WorkerInt.worker_int at 0x7f288dd56a60>
  certfile: None
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  chdir: /code
  pythonpath: /usr/bin/python3
  proxy_protocol: False
  keepalive: 2
  django_settings: None
  on_starting: <function OnStarting.on_starting at 0x7f288dd560d0>
  statsd_host: None
  cert_reqs: 0
  ciphers: TLSv1
  workers: 4
  graceful_timeout: 30
  bind: ['127.0.0.1:5000']
  pre_fork: <function Prefork.pre_fork at 0x7f288dd56598>
app-gunicorn stderr | [2016-05-20 15:12:08 +0000] [9] [INFO] Starting gunicorn 19.4.5
app-gunicorn stderr | [2016-05-20 15:12:08 +0000] [9] [DEBUG] Arbiter booted
app-gunicorn stderr | [2016-05-20 15:12:08 +0000] [9] [INFO] Listening at: http://127.0.0.1:5000 (9)
app-gunicorn stderr | [2016-05-20 15:12:08 +0000] [9] [INFO] Using worker: threads
app-gunicorn stderr | [2016-05-20 15:12:08 +0000] [13] [INFO] Booting worker with pid: 13
app-gunicorn stderr | [2016-05-20 15:12:08 +0000] [14] [INFO] Booting worker with pid: 14
app-gunicorn stderr | [2016-05-20 15:12:08 +0000] [20] [INFO] Booting worker with pid: 20
app-gunicorn stderr | [2016-05-20 15:12:09 +0000] [28] [INFO] Booting worker with pid: 28
app-gunicorn stderr | [2016-05-20 15:12:09 +0000] [9] [DEBUG] 4 workers
2016-05-20 15:12:14,042 INFO success: nginx entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
app-gunicorn stderr | [2016-05-20 15:13:39 +0000] [14] [DEBUG] GET /
nginx stdout | 192.168.99.1 - - [20/May/2016:15:13:39 +0000] "GET / HTTP/1.1" 200 970 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Kitematic/0.10.2 Chrome/45.0.2454.85 Electron/0.35.4 Safari/537.36"
app-gunicorn stderr | [2016-05-20 15:13:39 +0000] [14] [DEBUG] Closing connection.
2016-05-20 15:13:45,883 WARN received SIGTERM indicating exit request
2016-05-20 15:13:45,884 INFO waiting for nginx, app-gunicorn, stdout to die
app-gunicorn stderr | [2016-05-20 15:13:45 +0000] [9] [INFO] Handling signal: term
app-gunicorn stderr | [2016-05-20 15:13:45 +0000] [20] [INFO] Worker exiting (pid: 20)
app-gunicorn stderr | [2016-05-20 15:13:45 +0000] [28] [INFO] Worker exiting (pid: 28)
app-gunicorn stderr | [2016-05-20 15:13:45 +0000] [13] [INFO] Worker exiting (pid: 13)
app-gunicorn stderr | [2016-05-20 15:13:45 +0000] [14] [INFO] Worker exiting (pid: 14)
app-gunicorn stderr | [2016-05-20 15:13:46 +0000] [9] [INFO] Shutting down: Master
2016-05-20 15:13:46,214 INFO stopped: app-gunicorn (exit status 0)
nginx stdout | 2016/05/20 15:13:46 [notice] 8#0: signal 15 (SIGTERM) received, exiting
2016/05/20 15:13:46 [notice] 10#0: exiting
2016/05/20 15:13:46 [notice] 10#0: exit
2016-05-20 15:13:46,257 INFO stopped: nginx (exit status 0)
nginx stdout | 2016/05/20 15:13:46 [notice] 8#0: signal 17 (SIGCHLD) received
2016/05/20 15:13:46 [notice] 8#0: worker process 10 exited with code 0
2016/05/20 15:13:46 [notice] 8#0: exit
2016-05-20 15:13:46,258 INFO stopped: stdout (terminated by SIGTERM)
2016-05-20 15:13:46,632 CRIT Supervisor running as root (no user in config file)
2016-05-20 15:13:46,636 INFO supervisord started with pid 1
2016-05-20 15:13:47,639 INFO spawned: 'stdout' with pid 7
2016-05-20 15:13:47,641 INFO spawned: 'nginx' with pid 8
2016-05-20 15:13:47,643 INFO spawned: 'app-gunicorn' with pid 9
2016-05-20 15:13:49,154 INFO success: stdout entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-05-20 15:13:49,154 INFO success: app-gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
nginx stdout | 2016/05/20 15:13:47 [notice] 8#0: using the "epoll" event method
nginx stdout | 2016/05/20 15:13:47 [notice] 8#0: nginx/1.8.1
nginx stdout | 2016/05/20 15:13:47 [notice] 8#0: OS: Linux 4.4.8-boot2docker
nginx stdout | 2016/05/20 15:13:47 [notice] 8#0: getrlimit(RLIMIT_NOFILE): 1048576:1048576
nginx stdout | 2016/05/20 15:13:47 [notice] 8#0: start worker processes
nginx stdout | 2016/05/20 15:13:47 [notice] 8#0: start worker process 10
app-gunicorn stderr | [2016-05-20 15:13:47 +0000] [9] [DEBUG] Current configuration:
  limit_request_fields: 100
  logger_class: gunicorn.glogging.Logger
  statsd_prefix: 
  preload_app: False
  sendfile: None
  graceful_timeout: 30
  when_ready: <function WhenReady.when_ready at 0x7f24d848d400>
  certfile: None
  worker_class: sync
  suppress_ragged_eofs: True
  worker_tmp_dir: None
  spew: False
  on_reload: <function OnReload.on_reload at 0x7f24d848d268>
  group: 0
  worker_int: <function WorkerInt.worker_int at 0x7f24d848da60>
  backlog: 2048
  worker_connections: 1000
  chdir: /code
  on_starting: <function OnStarting.on_starting at 0x7f24d848d0d0>
  post_fork: <function Postfork.post_fork at 0x7f24d848d730>
  reload: False
  loglevel: debug
  logconfig: None
  proxy_allow_ips: ['127.0.0.1']
  check_config: False
  paste: None
  timeout: 30
  proxy_protocol: False
  syslog_addr: udp://localhost:514
  pythonpath: /usr/bin/python3
  workers: 4
  do_handshake_on_connect: False
  enable_stdio_inheritance: False
  pidfile: None
  pre_request: <function PreRequest.pre_request at 0x7f24d848df28>
  umask: 0
  on_exit: <function OnExit.on_exit at 0x7f24d8490598>
  raw_env: []
  proc_name: None
  django_settings: None
  forwarded_allow_ips: ['127.0.0.1']
  default_proc_name: app:app
  cert_reqs: 0
  worker_exit: <function WorkerExit.worker_exit at 0x7f24d8490268>
  config: None
  limit_request_line: 4094
  statsd_host: None
  keyfile: None
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f24d848d8c8>
  tmp_upload_dir: None
  worker_abort: <function WorkerAbort.worker_abort at 0x7f24d848dbf8>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f24d8490400>
  ca_certs: None
  syslog_prefix: None
  max_requests: 0
  errorlog: -
  ciphers: TLSv1
  accesslog: None
  ssl_version: 3
  bind: ['127.0.0.1:5000']
  max_requests_jitter: 0
  pre_fork: <function Prefork.pre_fork at 0x7f24d848d598>
  pre_exec: <function PreExec.pre_exec at 0x7f24d848dd90>
  post_request: <function PostRequest.post_request at 0x7f24d84900d0>
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  syslog: False
  daemon: False
  keepalive: 2
  syslog_facility: user
  user: 0
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-SSL': 'on', 'X-FORWARDED-PROTO': 'https'}
  threads: 2
  limit_request_field_size: 8190
app-gunicorn stderr | [2016-05-20 15:13:47 +0000] [9] [INFO] Starting gunicorn 19.4.5
app-gunicorn stderr | [2016-05-20 15:13:47 +0000] [9] [DEBUG] Arbiter booted
app-gunicorn stderr | [2016-05-20 15:13:47 +0000] [9] [INFO] Listening at: http://127.0.0.1:5000 (9)
app-gunicorn stderr | [2016-05-20 15:13:47 +0000] [9] [INFO] Using worker: threads
app-gunicorn stderr | [2016-05-20 15:13:47 +0000] [13] [INFO] Booting worker with pid: 13
app-gunicorn stderr | [2016-05-20 15:13:47 +0000] [14] [INFO] Booting worker with pid: 14
app-gunicorn stderr | [2016-05-20 15:13:48 +0000] [20] [INFO] Booting worker with pid: 20
app-gunicorn stderr | [2016-05-20 15:13:48 +0000] [21] [INFO] Booting worker with pid: 21
app-gunicorn stderr | [2016-05-20 15:13:48 +0000] [9] [DEBUG] 4 workers
2016-05-20 15:13:53,174 INFO success: nginx entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
app-gunicorn stderr | [2016-05-20 15:13:58 +0000] [20] [DEBUG] GET /
nginx stdout | 192.168.99.1 - - [20/May/2016:15:13:58 +0000] "GET / HTTP/1.1" 200 970 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
app-gunicorn stderr | [2016-05-20 15:13:58 +0000] [20] [DEBUG] Closing connection.
nginx stdout | 192.168.99.1 - - [20/May/2016:15:13:58 +0000] "GET /assets/nemo/css/theme.min.css HTTP/1.1" 200 3610 "http://192.168.99.100:32775/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
nginx stdout | 192.168.99.1 - - [20/May/2016:15:13:58 +0000] "GET /assets/nemo.secondary/css/theme-ext.css HTTP/1.1" 200 622 "http://192.168.99.100:32775/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
nginx stdout | 192.168.99.1 - - [20/May/2016:15:13:58 +0000] "GET /assets/nemo/images/nemo.png HTTP/1.1" 200 27811 "http://192.168.99.100:32775/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
app-gunicorn stderr | [2016-05-20 15:13:58 +0000] [21] [DEBUG] GET /favicon.ico
nginx stdout | 192.168.99.1 - - [20/May/2016:15:13:58 +0000] "GET /favicon.ico HTTP/1.1" 404 233 "http://192.168.99.100:32775/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
app-gunicorn stderr | [2016-05-20 15:13:58 +0000] [21] [DEBUG] Closing connection.
app-gunicorn stderr | [2016-05-20 15:16:06 +0000] [21] [DEBUG] GET /
nginx stdout | 192.168.99.1 - - [20/May/2016:15:16:06 +0000] "GET / HTTP/1.1" 200 970 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
app-gunicorn stderr | [2016-05-20 15:16:06 +0000] [21] [DEBUG] Closing connection.
app-gunicorn stderr | [2016-05-20 15:16:34 +0000] [20] [DEBUG] GET /
nginx stdout | 192.168.99.1 - - [20/May/2016:15:16:34 +0000] "GET / HTTP/1.1" 200 970 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Kitematic/0.10.2 Chrome/45.0.2454.85 Electron/0.35.4 Safari/537.36"
app-gunicorn stderr | [2016-05-20 15:16:34 +0000] [20] [DEBUG] Closing connection.
app-gunicorn stderr | [2016-05-20 15:17:13 +0000] [14] [DEBUG] GET /
nginx stdout | 192.168.99.1 - - [20/May/2016:15:17:13 +0000] "GET / HTTP/1.1" 200 970 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Kitematic/0.10.2 Chrome/45.0.2454.85 Electron/0.35.4 Safari/537.36"
app-gunicorn stderr | [2016-05-20 15:17:13 +0000] [14] [DEBUG] Closing connection.
2016-05-20 15:19:16,102 WARN received SIGTERM indicating exit request
2016-05-20 15:19:16,102 INFO waiting for nginx, app-gunicorn, stdout to die
app-gunicorn stderr | [2016-05-20 15:19:16 +0000] [9] [INFO] Handling signal: term
app-gunicorn stderr | [2016-05-20 15:19:16 +0000] [13] [INFO] Worker exiting (pid: 13)
app-gunicorn stderr | [2016-05-20 15:19:16 +0000] [14] [INFO] Worker exiting (pid: 14)
app-gunicorn stderr | [2016-05-20 15:19:16 +0000] [20] [INFO] Worker exiting (pid: 20)
app-gunicorn stderr | [2016-05-20 15:19:16 +0000] [21] [INFO] Worker exiting (pid: 21)
app-gunicorn stderr | [2016-05-20 15:19:16 +0000] [9] [INFO] Shutting down: Master
2016-05-20 15:19:16,431 INFO stopped: app-gunicorn (exit status 0)
nginx stdout | 2016/05/20 15:19:16 [notice] 8#0: signal 15 (SIGTERM) received, exiting
2016/05/20 15:19:16 [notice] 10#0: exiting
2016/05/20 15:19:16 [notice] 10#0: exit
2016-05-20 15:19:16,477 INFO stopped: nginx (exit status 0)
nginx stdout | 2016/05/20 15:19:16 [notice] 8#0: signal 17 (SIGCHLD) received
2016/05/20 15:19:16 [notice] 8#0: worker process 10 exited with code 0
2016/05/20 15:19:16 [notice] 8#0: exit
2016-05-20 15:19:16,478 INFO stopped: stdout (terminated by SIGTERM)
2016-05-20 15:21:49,141 CRIT Supervisor running as root (no user in config file)
2016-05-20 15:21:49,146 INFO supervisord started with pid 1
2016-05-20 15:21:50,149 INFO spawned: 'stdout' with pid 7
2016-05-20 15:21:50,151 INFO spawned: 'nginx' with pid 8
2016-05-20 15:21:50,153 INFO spawned: 'app-gunicorn' with pid 9
2016-05-20 15:21:51,706 INFO success: stdout entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-05-20 15:21:51,706 INFO success: app-gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
nginx stdout | 2016/05/20 15:21:50 [notice] 8#0: using the "epoll" event method
nginx stdout | 2016/05/20 15:21:50 [notice] 8#0: nginx/1.8.1
nginx stdout | 2016/05/20 15:21:50 [notice] 8#0: OS: Linux 4.4.8-boot2docker
nginx stdout | 2016/05/20 15:21:50 [notice] 8#0: getrlimit(RLIMIT_NOFILE): 1048576:1048576
nginx stdout | 2016/05/20 15:21:50 [notice] 8#0: start worker processes
nginx stdout | 2016/05/20 15:21:50 [notice] 8#0: start worker process 10
app-gunicorn stderr | [2016-05-20 15:21:50 +0000] [9] [DEBUG] Current configuration:
  ssl_version: 3
  max_requests_jitter: 0
  umask: 0
  proc_name: None
  user: 0
  when_ready: <function WhenReady.when_ready at 0x7f782237f400>
  raw_env: []
  ciphers: TLSv1
  graceful_timeout: 30
  bind: ['127.0.0.1:5000']
  cert_reqs: 0
  pre_fork: <function Prefork.pre_fork at 0x7f782237f598>
  max_requests: 0
  accesslog: None
  syslog_prefix: None
  limit_request_field_size: 8190
  post_fork: <function Postfork.post_fork at 0x7f782237f730>
  chdir: /code
  worker_tmp_dir: None
  pythonpath: /usr/bin/python3
  enable_stdio_inheritance: False
  secure_scheme_headers: {'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  pre_exec: <function PreExec.pre_exec at 0x7f782237fd90>
  config: None
  worker_connections: 1000
  worker_abort: <function WorkerAbort.worker_abort at 0x7f782237fbf8>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f7822382400>
  on_exit: <function OnExit.on_exit at 0x7f7822382598>
  logger_class: gunicorn.glogging.Logger
  worker_class: sync
  sendfile: None
  timeout: 30
  ca_certs: None
  tmp_upload_dir: None
  reload: False
  check_config: False
  backlog: 2048
  limit_request_line: 4094
  group: 0
  proxy_protocol: False
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f782237f8c8>
  worker_int: <function WorkerInt.worker_int at 0x7f782237fa60>
  preload_app: False
  suppress_ragged_eofs: True
  errorlog: -
  pre_request: <function PreRequest.pre_request at 0x7f782237ff28>
  default_proc_name: app:app
  syslog: False
  statsd_host: None
  statsd_prefix: 
  worker_exit: <function WorkerExit.worker_exit at 0x7f7822382268>
  threads: 2
  keepalive: 2
  on_starting: <function OnStarting.on_starting at 0x7f782237f0d0>
  loglevel: debug
  logconfig: None
  keyfile: None
  limit_request_fields: 100
  django_settings: None
  daemon: False
  paste: None
  workers: 4
  pidfile: None
  certfile: None
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  do_handshake_on_connect: False
  syslog_addr: udp://localhost:514
  syslog_facility: user
  on_reload: <function OnReload.on_reload at 0x7f782237f268>
  spew: False
  proxy_allow_ips: ['127.0.0.1']
  post_request: <function PostRequest.post_request at 0x7f78223820d0>
app-gunicorn stderr | [2016-05-20 15:21:50 +0000] [9] [INFO] Starting gunicorn 19.4.5
app-gunicorn stderr | [2016-05-20 15:21:50 +0000] [9] [DEBUG] Arbiter booted
app-gunicorn stderr | [2016-05-20 15:21:50 +0000] [9] [INFO] Listening at: http://127.0.0.1:5000 (9)
app-gunicorn stderr | [2016-05-20 15:21:50 +0000] [9] [INFO] Using worker: threads
app-gunicorn stderr | [2016-05-20 15:21:50 +0000] [13] [INFO] Booting worker with pid: 13
app-gunicorn stderr | [2016-05-20 15:21:50 +0000] [26] [INFO] Booting worker with pid: 26
app-gunicorn stderr | [2016-05-20 15:21:50 +0000] [27] [INFO] Booting worker with pid: 27
app-gunicorn stderr | [2016-05-20 15:21:50 +0000] [28] [INFO] Booting worker with pid: 28
app-gunicorn stderr | [2016-05-20 15:21:50 +0000] [9] [DEBUG] 4 workers
2016-05-20 15:21:55,726 INFO success: nginx entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
app-gunicorn stderr | [2016-05-20 15:22:01 +0000] [13] [DEBUG] GET /
nginx stdout | 192.168.99.1 - - [20/May/2016:15:22:01 +0000] "GET / HTTP/1.1" 200 970 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
app-gunicorn stderr | [2016-05-20 15:22:01 +0000] [13] [DEBUG] Closing connection.
app-gunicorn stderr | [2016-05-20 15:22:02 +0000] [28] [DEBUG] GET /favicon.ico
nginx stdout | 192.168.99.1 - - [20/May/2016:15:22:02 +0000] "GET /favicon.ico HTTP/1.1" 404 233 "http://192.168.99.100:32776/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
app-gunicorn stderr | [2016-05-20 15:22:02 +0000] [28] [DEBUG] Closing connection.

**Comment by annettegessner** [comment]
I tried the low memory variant today on my Mac at work, but it didn't work at all. I'll maybe try this at my Windows at home. Sorry, if I was being unclear about my two computers and their differing problems. Let's concentrate on the Uni Leipzig Macs for now, since the problem was with Thomas' and my Mac and - as already mentioned - COULD have something to do with our user directories not being local, but in a network. Maybe Thomas can specify again as he did in the hangout, if you want.

**Comment by PonteIneptique** [comment]
Could you try to rule out the issue by mounting an USB key with the
repository folder?

**Comment by ThomasK81** [comment]
Hi Thibault, 

For all Leipzig desktop macs it will be the following: 
They do have a network user folder called "u". Docker's Kitemate recognises this as the user folder and wants you to choose a folder within "u". Unfortunately, in the background the boot2docker VM wants you to have a local folder under "user" in order to access it. While you can generate this, Kitemate then won't let you add this folder, because it is not under what it recognises as the "user" folder under "u". Does this make sense? I think it all has to do with: https://github.com/boot2docker/boot2docker/issues/678

Maybe a solution would be to generate a small vagrant box alternative to boot2docker that boots up the docker image and not using Kitemate?

Cheers, 

Thomas

**Comment by ThomasK81** [comment]
For the same reasons, Thibault's suggestions of a USB workaround should work.

**Comment by annettegessner** [comment]
Thank you! I'll try the USB stick on Monday at my work Mac.

About my slow Windows machine at home: Correction: I have tried the low memory variant again and it is working perfectly and very fast! Sorry for misinforming before, Thibault, this tip was excellent! I was finally able to check, if the corrected CSEL works show up now and they do. B-)

**Comment by annettegessner** [comment]
Argh - Kitematic doesn't let me choose the USB stick, but says:
"Invalid directory. Volume directories must be under your Users directory"
Shoot, I really thought, this could solve the problem.
Since this issue should affect all Uni Leipzig computers, we either need to tell everybody to use another computer or we have to look for a workaround or an alternative.

**Comment by annettegessner** [comment]
Any other ideas, @PonteIneptique ?

**Comment by PonteIneptique** [comment]
Honnestly no, and this is based on your network installation. I am not a mac person nor a network engineer, which does not help. I guess you and @ThomasK81 need to dig this one, maybe potentially send a mail to the guys at Kinematic.

**Comment by fbaumgardt** [comment]
As I mentioned during the meeting -- the Leipzig Macs have a user called lguru which is local. It is also an administrative account, so possibly you just want to use that to set up another local account.

Also, https://beta.docker.com/ is a vast improvement over Boot2Docker. Though, i had mixed experiences with Kitematic. But running `docker start capitains` in a terminal shouldn't be an obstacle, right?

**Comment by annettegessner** [comment]
Almost forgot to post it here:
Thanks @fbaumgardt, your solution works! So to everybody who is using a network account on their computer (like at Uni Leipzig): switch to a local account (like the "local admin")!
