### ISSUE TITLE
Adding own texts to the repository

### ISSUE THREAD

**Issue by nevenjovanovic** [Capitains/docker-debian-capitains#6]
Provided I have a set of CTS-compliant and valid XML files such as [these](https://github.com/nevenjovanovic/hc-croala), what do I have to do to add them to the Docker Capitains deployment?

**Comment by PonteIneptique** [comment]
Hi @nevenjovanovic,
You need to get them in shape ! Which, apparently, should not be hard :) We'll see that at the workshop but the resource you're looking for are the guidelines ( http://capitains.github.io/pages/guidelines.html ) . There is some directory structure and some TEI implication but nothing hard to do.
